//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int KodPerson { get; set; }
        public Nullable<int> KodPolzovately { get; set; }
        public string LoginPolzovately { get; set; }
        public string Dolznost { get; set; }
        public string FIO { get; set; }
        public System.DateTime DataRozdeniy { get; set; }
        public string NomerTelephona { get; set; }
        public string Email { get; set; }
        public string Pol { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Polzovatel Polzovatel { get; set; }
    }
}
